// <auto-generated />
using System;
using MagicVilla_API.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230403022257_insertTabla")]
    partial class insertTabla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalle = "detalle villa",
                            ImagenUrl = "",
                            MetrosCuadrados = 50,
                            Nombre = "villa real",
                            Ocupantes = 5,
                            Tarifa = 200.0,
                            fechaActualizacion = new DateTime(2023, 4, 2, 21, 22, 57, 154, DateTimeKind.Local).AddTicks(1439),
                            fechaCreacion = new DateTime(2023, 4, 2, 21, 22, 57, 154, DateTimeKind.Local).AddTicks(1457)
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalle = "detalle villa2",
                            ImagenUrl = "",
                            MetrosCuadrados = 0,
                            Nombre = "villa real2",
                            Ocupantes = 54,
                            Tarifa = 2000.0,
                            fechaActualizacion = new DateTime(2023, 4, 2, 21, 22, 57, 154, DateTimeKind.Local).AddTicks(1462),
                            fechaCreacion = new DateTime(2023, 4, 2, 21, 22, 57, 154, DateTimeKind.Local).AddTicks(1463)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
